apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  replicas: 4
  minReadySeconds: 4
  selector:
    matchLabels:
      app: mydeployment
  template:
    metadata:
      name: mydeployment
      labels:
        app: mydeployment
    spec:
      #priorityClassName: unwichtigworkload
      containers:
      - name: image1
        image: erkules/nginxhostname
        resources:
          requests:
            #cpu: 10m
            #memory: 10000Mi
            #ephemeral-storage: "20Mi"
              #          limits:
              #            cpu: 50m
              #            memory: 100Mi
              #            ephemeral-storage: "20Mi"
