apiVersion: v1
kind: Namespace
metadata:
  name: erkan
---

apiVersion: v1
kind: ServiceAccount
metadata:
    name: erkan
    namespace: erkan
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: erkan
  namespace: erkan
subjects:
- kind: ServiceAccount
  name: erkan
- kind: User
  name: erkan
roleRef:
  kind: ClusterRole
  name: admin 
  apiGroup: rbac.authorization.k8s.io

